# Basic
title: MsSmart
# subtitle: Stay hungry，stay foolish
#welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
welcome_message: 保持求知欲，保持赤子心
description: 程序媛一枚，就职于美团，从事iOS开发工作</br>沉淀技术，记录成长，感受生活，不忘初心
#creator: <a href="http://onev.cat">@onevcat</a>

#url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: purple

# The blog button should not be removed.
blog_button:
    title: 博客
    description: Visit blog

# Navigation buttons in the front page.
# nav:
    # - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: MsSmart
    # duoshuo: 
    
# Social
social:
    # weibo: MsSmart
    github: MsSmart
    # twitter: onevcat
    # gplus: 107108267983477358170
    mail: guositong2006@126.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
